version: "3.7"
services:
  bot:
    image: ghcr.io/modmail-dev/modmail:master
    restart: always
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb+srv://scc:zl3FgVm5ltDC9apx@scclogs.sr0abcz.mongodb.net/
